name: VPS with LocalTunnel

on: [workflow_dispatch]

jobs:
  localtunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js & LocalTunnel
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
          sudo npm install -g localtunnel

      - name: Run server
        run: |
          nohup python3 -m http.server 8080 &

      - name: Start tunnel
        run: |
          nohup lt --port 8080 --subdomain mycustomname > tunnel.log &
          sleep 5
          cat tunnel.log
