name: VPS with Cloudflared

on: [workflow_dispatch]

jobs:
  start-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

      - name: Run simple HTTP server (example)
        run: |
          sudo apt update
          sudo apt install -y python3
          nohup python3 -m http.server 8080 &

      - name: Start Cloudflared tunnel
        run: |
          nohup cloudflared tunnel --url http://localhost:8080 &
          sleep 5
          curl -s https://trycloudflare.com > url.txt || true
          cat url.txt
