name: Cloudflared Tunnel VPS

on: [workflow_dispatch]

jobs:
  run-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

      - name: Start HTTP Server
        run: |
          nohup python3 -m http.server 8080 &

      - name: Start Cloudflared Tunnel
        run: |
          nohup cloudflared tunnel --url http://localhost:8080 > cloudflared.log 2>&1 &
          sleep 10
          cat cloudflared.log | grep "https://" || echo "Туннель не запущен"
